version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-express
    environment:
      SA_PASSWORD: "Admin@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  webapp:
    build: .
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql-server;Database=HahnTaskManager;User Id=sa;Password=Admin@123;TrustServerCertificate=true;"
    depends_on:
      - sql-server

volumes:
  sql-data: